import { Language } from "@/shared/i18n/translations";

export type ListenCopy = {
  title: string; subtitle: string; continue: string; resume: string; saved: string; saveLater: string; savedTitle: string; savedEmptyTitle: string; savedEmptyText: string; libraryPreview: string; unavailable: string; unavailableText: string; back: string; all: string; minutes: string; resumeFrom: string; coming: string; shareVoice: string; shareVoiceText: string; titleField: string; titlePlaceholder: string; aboutField: string; aboutPlaceholder: string; categoryField: string; recordingField: string; saveDraft: string; draftSaved: string; submitReview: string; reviewUnavailable: string; record: string; uploadAudio: string; pause: string; resumeRecording: string; stop: string; recordAgain: string; deleteRecording: string; preview: string; drafts: string; noDrafts: string; devLabel: string;
  sections: Record<string, { title: string; description: string; empty: string }>;
  filters: Record<string, string[]>;
  communityCategories: string[];
};

const en: ListenCopy = {
  title: "I want to listen", subtitle: "Choose what you want to hear right now.", continue: "Continue listening", resume: "Resume", saved: "Saved", saveLater: "Save for later", savedTitle: "Saved for Later", savedEmptyTitle: "Nothing saved yet", savedEmptyText: "Save something that speaks to you and come back whenever you're ready.", libraryPreview: "Library preview", unavailable: "This audio isn't available right now.", unavailableText: "The reviewed Plekai audio library is being prepared. Please try again later.", back: "Back", all: "All", minutes: "min", resumeFrom: "Resume from", coming: "Coming soon", shareVoice: "Share your voice", shareVoiceText: "Offer a gentle story or insight for others walking through pain.", titleField: "Title", titlePlaceholder: "Give your recording a gentle title…", aboutField: "About your recording", aboutPlaceholder: "Share a little about what inspired you to record…", categoryField: "Category", recordingField: "Your recording", saveDraft: "Save draft", draftSaved: "Draft saved privately on this device.", submitReview: "Submit for review", reviewUnavailable: "Community submissions are being prepared. Your recording can be saved as a draft for now.", record: "Start recording", uploadAudio: "Upload audio", pause: "Pause", resumeRecording: "Resume", stop: "Stop", recordAgain: "Record again", deleteRecording: "Delete recording", preview: "Preview recording", drafts: "Your drafts", noDrafts: "Saved community drafts will appear here.", devLabel: "Development preview — real audio pending",
  sections: {
    practices: { title: "Audio Practices", description: "Guided audio for reflection, grief, and the seasons of life.", empty: "Audio practices are coming soon. Guided reflections will appear here as the Plekai library grows." },
    healing: { title: "Sound Healing", description: "Calming sound experiences for quiet, rest, and grounding.", empty: "Sound sessions are being prepared." },
    science: { title: "Science Insights", description: "Listen to short educational insights about grief, healing, and the mind.", empty: "Audio insights will appear here soon." },
    nature: { title: "Nature Sounds", description: "Rain, ocean, forest, and night sounds for calm and rest.", empty: "Nature sounds are being prepared." },
    music: { title: "Music", description: "Gentle and reflective music for quiet moments.", empty: "Music for quiet moments is coming soon." },
    voices: { title: "Voices Through the Valley", description: "Stories and advice from people walking through pain.", empty: "Community voices will appear here as stories are shared and reviewed." },
  },
  filters: { practices: ["All", "About Life", "About Children", "Future Self"], healing: ["All", "Calm", "Sleep", "Release", "Focus", "Energy"], science: ["All", "Grief", "Memory", "Stress", "Sleep", "Healing", "Relationships"], nature: ["All", "Rain", "Ocean", "Forest", "Night"], music: ["All", "Instrumental", "Piano", "Strings", "Hopeful"], voices: ["All", "Story", "Advice", "Faith", "Hope"], saved: ["All", "Practices", "Healing", "Science", "Nature", "Music", "Voices"] }, communityCategories: ["Story", "Advice", "Faith", "Hope"],
};

const uk: ListenCopy = {
  ...en, title: "Я хочу слухати", subtitle: "Обери, що хочеться почути саме зараз.", continue: "Продовжити слухати", resume: "Продовжити", saved: "Збережено", saveLater: "Зберегти на потім", savedTitle: "Збережене на потім", savedEmptyTitle: "Поки нічого не збережено", savedEmptyText: "Збережи те, що відгукується, і повернися, коли будеш готова або готовий.", libraryPreview: "Попередній вигляд бібліотеки", unavailable: "Це аудіо зараз недоступне.", unavailableText: "Перевірена аудіобібліотека Plekai готується. Спробуй пізніше.", back: "Назад", all: "Усі", minutes: "хв", resumeFrom: "Продовжити з", coming: "Незабаром", shareVoice: "Поділися голосом", shareVoiceText: "Запропонуй дбайливу історію або думку тим, хто проходить крізь біль.", titleField: "Назва", titlePlaceholder: "Дай запису дбайливу назву…", aboutField: "Про запис", aboutPlaceholder: "Трохи розкажи, що надихнуло тебе записати…", categoryField: "Категорія", recordingField: "Твій запис", saveDraft: "Зберегти чернетку", draftSaved: "Чернетку приватно збережено на цьому пристрої.", submitReview: "Надіслати на перевірку", reviewUnavailable: "Подання спільноти ще готуються. Наразі запис можна зберегти як чернетку.", record: "Почати запис", uploadAudio: "Завантажити аудіо", pause: "Пауза", resumeRecording: "Продовжити", stop: "Зупинити", recordAgain: "Записати знову", deleteRecording: "Видалити запис", preview: "Прослухати запис", drafts: "Твої чернетки", noDrafts: "Тут з’являться збережені чернетки.", devLabel: "Попередня версія — справжнє аудіо готується",
  sections: {
    practices: { title: "Аудіопрактики", description: "Керовані аудіо для роздумів, горювання та різних періодів життя.", empty: "Аудіопрактики незабаром з’являться. Бібліотека Plekai поступово зростатиме." },
    healing: { title: "Цілющі звуки", description: "Спокійні звукові сесії для тиші, відпочинку й опори.", empty: "Звукові сесії готуються." }, science: { title: "Наукові пояснення", description: "Короткі аудіопояснення про горювання, зцілення та розум.", empty: "Аудіопояснення з’являться незабаром." }, nature: { title: "Звуки природи", description: "Дощ, океан, ліс і нічні звуки для спокою та відпочинку.", empty: "Звуки природи готуються." }, music: { title: "Музика", description: "Ніжна музика для тихих моментів.", empty: "Музика для тихих моментів з’явиться незабаром." }, voices: { title: "Голоси крізь долину", description: "Історії та поради людей, які проходять крізь біль.", empty: "Голоси спільноти з’являться після подання та перевірки історій." },
  },
  filters: { practices: ["Усі", "Про життя", "Про дітей", "Майбутнє я"], healing: ["Усі", "Спокій", "Сон", "Відпустити", "Фокус", "Енергія"], science: ["Усі", "Горювання", "Пам’ять", "Стрес", "Сон", "Зцілення", "Стосунки"], nature: ["Усі", "Дощ", "Океан", "Ліс", "Ніч"], music: ["Усі", "Інструментальна", "Піаніно", "Струнні", "Надія"], voices: ["Усі", "Історія", "Порада", "Віра", "Надія"], saved: ["Усі", "Практики", "Звуки", "Наука", "Природа", "Музика", "Голоси"] }, communityCategories: ["Історія", "Порада", "Віра", "Надія"],
};

const ru: ListenCopy = {
  ...en, title: "Я хочу слушать", subtitle: "Выбери, что хочется услышать прямо сейчас.", continue: "Продолжить слушать", resume: "Продолжить", saved: "Сохранено", saveLater: "Сохранить на потом", savedTitle: "Сохранённое на потом", savedEmptyTitle: "Пока ничего не сохранено", savedEmptyText: "Сохрани то, что откликается, и вернись, когда будешь готова или готов.", libraryPreview: "Предпросмотр библиотеки", unavailable: "Это аудио сейчас недоступно.", unavailableText: "Проверенная аудиобиблиотека Plekai готовится. Попробуй позже.", back: "Назад", all: "Все", minutes: "мин", resumeFrom: "Продолжить с", coming: "Скоро", shareVoice: "Поделись голосом", shareVoiceText: "Предложи бережную историю или мысль тем, кто проходит через боль.", titleField: "Название", titlePlaceholder: "Дай записи бережное название…", aboutField: "О записи", aboutPlaceholder: "Немного расскажи, что вдохновило тебя записать…", categoryField: "Категория", recordingField: "Твоя запись", saveDraft: "Сохранить черновик", draftSaved: "Черновик приватно сохранён на этом устройстве.", submitReview: "Отправить на проверку", reviewUnavailable: "Отправка материалов сообщества ещё готовится. Пока запись можно сохранить как черновик.", record: "Начать запись", uploadAudio: "Загрузить аудио", pause: "Пауза", resumeRecording: "Продолжить", stop: "Остановить", recordAgain: "Записать снова", deleteRecording: "Удалить запись", preview: "Прослушать запись", drafts: "Твои черновики", noDrafts: "Здесь появятся сохранённые черновики.", devLabel: "Предварительная версия — настоящее аудио готовится",
  sections: {
    practices: { title: "Аудиопрактики", description: "Аудио для размышлений, горевания и разных периодов жизни.", empty: "Аудиопрактики скоро появятся. Библиотека Plekai будет постепенно расти." }, healing: { title: "Целительные звуки", description: "Спокойные звуковые сессии для тишины, отдыха и опоры.", empty: "Звуковые сессии готовятся." }, science: { title: "Научные объяснения", description: "Короткие аудиообъяснения о горевании, исцелении и разуме.", empty: "Аудиообъяснения появятся скоро." }, nature: { title: "Звуки природы", description: "Дождь, океан, лес и ночные звуки для спокойствия и отдыха.", empty: "Звуки природы готовятся." }, music: { title: "Музыка", description: "Нежная музыка для тихих моментов.", empty: "Музыка для тихих моментов скоро появится." }, voices: { title: "Голоса сквозь долину", description: "Истории и советы людей, которые проходят через боль.", empty: "Голоса сообщества появятся после отправки и проверки историй." },
  },
  filters: { practices: ["Все", "О жизни", "О детях", "Будущее я"], healing: ["Все", "Спокойствие", "Сон", "Отпустить", "Фокус", "Энергия"], science: ["Все", "Горевание", "Память", "Стресс", "Сон", "Исцеление", "Отношения"], nature: ["Все", "Дождь", "Океан", "Лес", "Ночь"], music: ["Все", "Инструментальная", "Пианино", "Струнные", "Надежда"], voices: ["Все", "История", "Совет", "Вера", "Надежда"], saved: ["Все", "Практики", "Звуки", "Наука", "Природа", "Музыка", "Голоса"] }, communityCategories: ["История", "Совет", "Вера", "Надежда"],
};

export const listenCopy: Record<Language, ListenCopy> = { en, uk, ru };
